### ISSUE TITLE
Solve the problem of inconsistency with 'data' parameter

### ISSUE THREAD

**Issue by adriaroca** [omatech/laravel-autoview#1]
Using the first parameter of the helper as alternative name of the view and to pass data at the same time, can cause confusion.

It is necessary to look for a solution that allows us to send the data to the view without depending on a parameter.

One option would be to use the `with` method of the class `Illuminate\View\View`. For example:

```
    public function test()
    {
        $title = 'Test title';
        $subtitle = 'Test subtitle';
        
        return autoview()->with(compact('title', 'subtitle'));
    }
```

**Comment by aponscat** [comment]
era broma, ho canviaria directament :)

Agusti Pons
omatech.com

________________________________
De: Adrià Roca <notifications@github.com>
Enviado: jueves, diciembre 13, 2018 12:47
Para: omatech/laravel-autoview
CC: Subscribed
Asunto: [omatech/laravel-autoview] Solve the problem of inconsistency with 'data' parameter (#1)


Using the first parameter of the helper as alternative name of the view and to pass data at the same time, can cause confusion.

It is necessary to look for a solution that allows us to send the data to the view without depending on a parameter.

One option would be to use the with method of the class Illuminate\View\View. For example:

    public function test()
    {
        $title = 'Test title';
        $subtitle = 'Test subtitle';

        return autoview()->with(compact('title', 'subtitle'));
    }

**Comment by adriaroca** [comment]
Solved. The second parameter has been removed.
